<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "fleet"
 *
 * Auto generated by Extension Builder 2017-04-11
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'fleet',
    'description' => 'Command line utility to provide system information for Fleet',
    'category' => 'services',
    'author' => 'Daniel Corn',
    'author_email' => 'info@cundd.net',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '0.1.0',
    'constraints' => [
        'depends' => [
            'typo3' => '6.2.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
